#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

nitrogen --restore &
xsetroot -cursor_name left_ptr &
bspc config focus_follows_pointer true
exec $HOME/.config/polybar/launch.sh &
/usr/lib/at-spi-bus-launcher --launch-immediately &
flameshot &

exec systemctl --user import-environment &

picom -b &
LC_ALL=en_US.UTF-8 fcitx &
dunst &

bspc config border_width           1
bspc config window_gap             18

bspc config left_padding           40
bspc config right_padding          40
bspc config top_padding            86
bspc config bottom_padding         40

bspc config split_ratio            0.52
bspc config borderless_monocle     true
bspc config gapless_monocle        false

bspc config focused_border_color   "#B4BEFE"
bspc config normal_border_color    "#6C7086"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Google-chrome desktop='^2'
bspc rule -a URxvt desktop='^1'
bspc rule -a discord desktop='^3'
bspc rule -a Thunar desktop='^4'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
